name: Check README Links

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed
  workflow_dispatch:

env:
  URL: https://victoria.dev/link-snitch/

jobs:
  check_links:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run Link Snitch on README
        uses: ./ # Refers to the current action in this repository
        with:
          url: ${{ env.URL }}
